# Generated by Django 3.1.4 on 2022-02-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('smtp_server', models.CharField(max_length=100, verbose_name='SMTP SERVER')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('imap_server', models.CharField(default='imap.gmail.com', max_length=100, verbose_name='IMAP SERVER')),
                ('imap_port', models.IntegerField(default=993, verbose_name='IMAP Port')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
